CREATE CONSTRAINT ON (h:Host) ASSERT h.host_id IS UNIQUE;
CREATE CONSTRAINT ON (l:Listing) ASSERT l.lising_id IS UNIQUE;
CREATE CONSTRAINT ON (u:User) ASSERT u.user_id IS UNIQUE;
CREATE CONSTRAINT ON (a:Amenity) ASSERT a.name IS UNIQUE;
CREATE CONSTRAINT ON (c:City) ASSERT c.name IS UNIQUE;
CREATE CONSTRAINT ON (s:State) ASSERT s.code IS UNIQUE;
CREATE CONSTRAINT ON (c:Country) ASSERT c.code IS UNIQUE;
CREATE CONSTRAINT ON (r:Review) ASSERT r.review_id IS UNIQUE;
